version: '3.8'

services:

  node:
    image:  c0211d492894
    ports:
      - "80:80"

  postgres:
    build: Datenbank
    environment:
      POSTGRES_USER: julian1234
      POSTGRES_PASSWORD: baum
      POSTGRES_DB: gruenflaeche
    ports:
      - "5432:5432"

  backend:
    build: backend
    hostname: backend
    ports:
      - "3000:5000"
      - "5000:5000"
    environment:
      PYTHONPATH: /app/Rest-API
    command: gunicorn --bind 0.0.0.0:5000 Rest-API.api:app       

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=julian1234
      - INFLUXDB_ADMIN_PASSWORD=gruenflaeche
    ports:
      - '8086:8086'
    volumes:
      - influxdb:/var/lib/influxdb
  
  telegraf:
     image: telegraf
     container_name: telegraf
     restart: always
     volumes:
     - /C/Telegraf:/etc/telegraf
     depends_on:
      - influxdb
     links:
      - influxdb
     ports:
     - '8125:8125'
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '9000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      
volumes:
  grafana_data: {}
  influxdb: {}
